# Generated by Django 4.0.3 on 2022-04-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_wallet_holder_alter_transaction_transaction_id_and_more'),
        ('accounts', '0005_alter_account_options_alter_account_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.wallet'),
        ),
    ]
