# Generated by Django 4.0.3 on 2022-04-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer_id',
            new_name='customer_merchant_id',
        ),
    ]
