# Generated by Django 4.0.3 on 2022-04-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='labourer_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
