# Generated by Django 4.0.3 on 2022-04-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_labourer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('disable_account', 'Can disable account'), ('view_customer', 'Can View Customer'), ('view_labourer', 'Can View Labourer'), ('view_admin', 'Can View Admins'), ('delete_labourer', 'Can Delete Labourer'), ('delete_admin', 'Can Delete Staff Member'), ('delete_customer', 'Can Delete Customer')]},
        ),
    ]
