# Generated by Django 4.0.3 on 2022-03-09 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('charge', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mode_of_payment', models.CharField(max_length=200)),
                ('date_of_service', models.DateTimeField(auto_now_add=True)),
                ('date_of_completion', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('labourer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labourer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
