# Generated by Django 4.0.3 on 2022-03-09 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Product Image')),
                ('min_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Maximum Price')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=50, verbose_name='Wallet ID')),
                ('main_balance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Main Balance')),
                ('available_balance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='available Balance')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='labourer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, verbose_name='Wallet ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount')),
                ('payment_mode', models.CharField(max_length=50, verbose_name='Mode of Payment')),
                ('service', models.CharField(max_length=50, verbose_name='Service Rendered')),
                ('payment', models.CharField(max_length=50, verbose_name='Payment Status')),
                ('payment_date', models.DateTimeField(verbose_name='Payment date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('labourer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Labourer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.wallet')),
            ],
        ),
    ]
