# Generated by Django 4.0.3 on 2022-04-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_wallet_alter_service_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
