# Generated by Django 4.0.3 on 2022-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_transaction_payment_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(default='MTN', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
