# Generated by Django 4.0.3 on 2022-04-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_wallet_holder_alter_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='available Balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='main_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='Main Balance'),
        ),
    ]
