# Generated by Django 4.0.3 on 2022-04-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_wallet_available_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('make_payment', 'Can Make Payment'), ('receive_payment', 'Can Receive Payment')]},
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
