# Generated by Django 4.0.3 on 2022-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_disbursement_disbursement_type_disbursement_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='6v4qad1zdc', max_length=12),
        ),
    ]
