# Generated by Django 4.0.3 on 2022-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_service_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='pwut4997fr', max_length=12),
        ),
    ]
