# Generated by Django 4.0.3 on 2022-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_service_status_alter_service_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='is748l9vy1', max_length=12),
        ),
    ]
