# Generated by Django 4.0.3 on 2022-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_jobcategory_alter_service_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='4vi0yohq6x', max_length=12),
        ),
    ]
