# Generated by Django 4.0.3 on 2022-05-07 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_service_accepted_alter_service_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='s184en8nmt', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='labourer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Labourer'),
        ),
    ]
