# Generated by Django 4.0.3 on 2022-05-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0021_transaction_job_alter_service_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='1dw743xw4m', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Rendered'),
        ),
    ]
