# Generated by Django 4.0.3 on 2022-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_service_job_id_alter_transaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='yq8qdeztcj', max_length=12),
        ),
    ]
