# Generated by Django 4.0.3 on 2022-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_service_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='jmpsxhd4qg', max_length=12),
        ),
    ]
