# Generated by Django 4.0.3 on 2022-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_service_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='completion_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='v9g00bww5t', max_length=12),
        ),
    ]
