# Generated by Django 4.0.3 on 2022-05-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_service_completion_confirmed_alter_service_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='b3aubp2ofa', max_length=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
