# Generated by Django 4.0.3 on 2022-05-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_service_job_id_alter_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='3312kb8d5q', max_length=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
