# Generated by Django 4.0.3 on 2022-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_service_charge_alter_service_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='1cds9fe5r5', max_length=12),
        ),
    ]
