# Generated by Django 4.0.3 on 2022-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_service_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_id',
            field=models.CharField(default='lk961knzms', max_length=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='mode_of_payment',
            field=models.CharField(default='MOMO', max_length=20),
        ),
    ]
